//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InitiateAPI.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ULT_BPMEntities : DbContext
    {
        public ULT_BPMEntities()
            : base("name=ULT_BPMEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<vw_Completed> vw_Completed { get; set; }
        public virtual DbSet<vw_InboxProveedores> vw_InboxProveedores { get; set; }
        public virtual DbSet<vw_CompletedProveedores> vw_CompletedProveedores { get; set; }
        public virtual DbSet<vw_Inbox> vw_Inbox { get; set; }
    }
}
