//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InitiateAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_InboxProveedores
    {
        public string PROCESSNAME { get; set; }
        public Nullable<int> INCIDENT { get; set; }
        public string STEPID { get; set; }
        public string STEPLABEL { get; set; }
        public string TASKID { get; set; }
        public string TASKUSER { get; set; }
        public Nullable<int> STATUS { get; set; }
        public string Process { get; set; }
        public string CodigoProceso { get; set; }
        public string ObjetoContratacion { get; set; }
        public string Step { get; set; }
        public Nullable<System.DateTime> FechaProgramada { get; set; }
        public Nullable<int> PROCESSVERSION { get; set; }
    }
}
